// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/docker.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_api_docker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_api_docker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_docker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{2}
}

type Container struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Container) Reset() {
	*x = Container{}
	mi := &file_api_docker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Container) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Container) ProtoMessage() {}

func (x *Container) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Container.ProtoReflect.Descriptor instead.
func (*Container) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{3}
}

func (x *Container) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Container) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Container) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Container) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ContainerList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*Container           `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerList) Reset() {
	*x = ContainerList{}
	mi := &file_api_docker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerList) ProtoMessage() {}

func (x *ContainerList) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerList.ProtoReflect.Descriptor instead.
func (*ContainerList) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerList) GetContainers() []*Container {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerID) Reset() {
	*x = ContainerID{}
	mi := &file_api_docker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerID) ProtoMessage() {}

func (x *ContainerID) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerID.ProtoReflect.Descriptor instead.
func (*ContainerID) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResponse) Reset() {
	*x = OperationResponse{}
	mi := &file_api_docker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResponse) ProtoMessage() {}

func (x *OperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResponse.ProtoReflect.Descriptor instead.
func (*OperationResponse) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{6}
}

func (x *OperationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ContainerLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          string                 `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerLogs) Reset() {
	*x = ContainerLogs{}
	mi := &file_api_docker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerLogs) ProtoMessage() {}

func (x *ContainerLogs) ProtoReflect() protoreflect.Message {
	mi := &file_api_docker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerLogs.ProtoReflect.Descriptor instead.
func (*ContainerLogs) Descriptor() ([]byte, []int) {
	return file_api_docker_proto_rawDescGZIP(), []int{7}
}

func (x *ContainerLogs) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

var File_api_docker_proto protoreflect.FileDescriptor

const file_api_docker_proto_rawDesc = "" +
	"\n" +
	"\x10api/docker.proto\x12\x03api\"E\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\a\n" +
	"\x05Empty\"_\n" +
	"\tContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"?\n" +
	"\rContainerList\x12.\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x0e.api.ContainerR\n" +
	"containers\"\x1d\n" +
	"\vContainerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11OperationResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"#\n" +
	"\rContainerLogs\x12\x12\n" +
	"\x04logs\x18\x01 \x01(\tR\x04logs2\xdd\x02\n" +
	"\rDockerService\x121\n" +
	"\bRegister\x12\x10.api.AuthRequest\x1a\x11.api.AuthResponse\"\x00\x12.\n" +
	"\x05Login\x12\x10.api.AuthRequest\x1a\x11.api.AuthResponse\"\x00\x122\n" +
	"\x0eListContainers\x12\n" +
	".api.Empty\x1a\x12.api.ContainerList\"\x00\x12<\n" +
	"\x0eStartContainer\x12\x10.api.ContainerID\x1a\x16.api.OperationResponse\"\x00\x12;\n" +
	"\rStopContainer\x12\x10.api.ContainerID\x1a\x16.api.OperationResponse\"\x00\x12:\n" +
	"\x10GetContainerLogs\x12\x10.api.ContainerID\x1a\x12.api.ContainerLogs\"\x00B\x14Z\x12docker-service/apib\x06proto3"

var (
	file_api_docker_proto_rawDescOnce sync.Once
	file_api_docker_proto_rawDescData []byte
)

func file_api_docker_proto_rawDescGZIP() []byte {
	file_api_docker_proto_rawDescOnce.Do(func() {
		file_api_docker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_docker_proto_rawDesc), len(file_api_docker_proto_rawDesc)))
	})
	return file_api_docker_proto_rawDescData
}

var file_api_docker_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_docker_proto_goTypes = []any{
	(*AuthRequest)(nil),       // 0: api.AuthRequest
	(*AuthResponse)(nil),      // 1: api.AuthResponse
	(*Empty)(nil),             // 2: api.Empty
	(*Container)(nil),         // 3: api.Container
	(*ContainerList)(nil),     // 4: api.ContainerList
	(*ContainerID)(nil),       // 5: api.ContainerID
	(*OperationResponse)(nil), // 6: api.OperationResponse
	(*ContainerLogs)(nil),     // 7: api.ContainerLogs
}
var file_api_docker_proto_depIdxs = []int32{
	3, // 0: api.ContainerList.containers:type_name -> api.Container
	0, // 1: api.DockerService.Register:input_type -> api.AuthRequest
	0, // 2: api.DockerService.Login:input_type -> api.AuthRequest
	2, // 3: api.DockerService.ListContainers:input_type -> api.Empty
	5, // 4: api.DockerService.StartContainer:input_type -> api.ContainerID
	5, // 5: api.DockerService.StopContainer:input_type -> api.ContainerID
	5, // 6: api.DockerService.GetContainerLogs:input_type -> api.ContainerID
	1, // 7: api.DockerService.Register:output_type -> api.AuthResponse
	1, // 8: api.DockerService.Login:output_type -> api.AuthResponse
	4, // 9: api.DockerService.ListContainers:output_type -> api.ContainerList
	6, // 10: api.DockerService.StartContainer:output_type -> api.OperationResponse
	6, // 11: api.DockerService.StopContainer:output_type -> api.OperationResponse
	7, // 12: api.DockerService.GetContainerLogs:output_type -> api.ContainerLogs
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_docker_proto_init() }
func file_api_docker_proto_init() {
	if File_api_docker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_docker_proto_rawDesc), len(file_api_docker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_docker_proto_goTypes,
		DependencyIndexes: file_api_docker_proto_depIdxs,
		MessageInfos:      file_api_docker_proto_msgTypes,
	}.Build()
	File_api_docker_proto = out.File
	file_api_docker_proto_goTypes = nil
	file_api_docker_proto_depIdxs = nil
}
